"""Add created_at, updated_at

Revision ID: 4d8ba1ba6466
Revises: 246d8e83fc1f
Create Date: 2025-04-07 23:37:00.156163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8ba1ba6466'
down_revision = '246d8e83fc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
